### ISSUE TITLE
Y-axis ticks are not coming properly

### ISSUE THREAD

**Issue by Prashant-Kamboj** [cerner/carbon-graphs#116]
**Describe the bug**
The y-axis ticks are not coming correctly even if we are passing values array in the ticks of the y-axis and the tick spacing is also not proper.

**To Reproduce**
In the graph input json give the y as 

y: {
        label: 'y-axis',
        lowerLimit: 60,
        upperLimit: 210,
        ticks: {
          values: [60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210],
        },
      },

the y-axis is giving top and bottom spacing in the ticks below 60 and above 210 which should not be there

**Expected behavior**
The y-axis ticks should start from 60 and go till 210. as the lower, upper limit and the ticks provided.( division should be as per the ticks are given in the values array)

**Screenshots**

![image](https://user-images.githubusercontent.com/53033168/69247106-dfda8f80-0bcf-11ea-8791-6062dcdb7d95.png)

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome]

**Additional context**
The y-axis is giving top and bottom spacing in the ticks below 60 and above 210 which should not be there.

**Comment by pranav300** [comment]
@Prashant-Kamboj 

The graph in the screenshot is being created when you pas inline values to upper and lower limit i.e 210 and 60. But the value that is being passed via `lowerLimitValue` and `upperLimitValue` is 90 and 190, you can check it [here](https://github.cerner.com/aeon-womenshealth/partogram-js/blob/master/src/components/carbonHelpers.js#L75-L76).

And due to which the limit is extended from expected 60-210 to 30-240. And the excess space is to accommodate the extended limit.

This is [where](https://github.cerner.com/aeon-womenshealth/partogram-js/blob/master/src/components/fetal-heart-rate/FetalHeartRateGraph.jsx#L152-L153) the upper and lower limit gets calculated.

Check the [constants](https://github.cerner.com/aeon-womenshealth/partogram-js/blob/master/src/constants.js) as well once.

**Comment by Prashant-Kamboj** [comment]
Even if we pass the lower limit and upper limit as 60 and upper limit as 220 then also after loading the data the graph auto-scales to 40 - 240.

Please don't go with the lowerLimitValue and upperLimitValue is 90 and 190. I am giving lower and upper limit directly in the input json of the graph as 60-220 then also it is showing the same behavior.

**Comment by abhijit945** [comment]
This is working as expected. 

https://codesandbox.io/s/intelligent-mirzakhani-vj0eq

For more information on how to control ticks better please go over [this](https://github.com/cerner/carbon-graphs/blob/master/docs/helpers/Axes.md) documentation. 
Specifically, `rangeRounding` and `padDomain`.

**With both turned off**

**Input**
```js
y: {
  label: "A",
  lowerLimit: 10,
  upperLimit: 300,
  rangeRounding: false,
  padDomain: false
}
```

![image](https://user-images.githubusercontent.com/4908886/72095599-5fd2cb00-32de-11ea-939f-9247f1e360f6.png)

**With default parameters**

**Input**

```js
y: {
  label: "A",
  lowerLimit: 10,
  upperLimit: 300
}
```
![image](https://user-images.githubusercontent.com/4908886/72095659-8a248880-32de-11ea-91d4-318c6a56500f.png)


**Your case**

![image](https://user-images.githubusercontent.com/4908886/72095975-f69f8780-32de-11ea-8802-a8ddfea7528b.png)

**Comment by Prashant-Kamboj** [comment]
Thanks @abhijit945
