### ISSUE TITLE
Timeline displays data points(values) that are in the past

### ISSUE THREAD

**Issue by dp21g** [cerner/carbon-graphs#136]
**Describe the bug**
When values are added to the timeline which are in the past compared to the upper and lower limit, they are still displayed on the timeline. However, the values are not displayed when they in the future, when compared to the upper and lower limit.

**To Reproduce**
See working example below:
https://codesandbox.io/s/data-points-displaying-outside-range-9rvy4

**Expected behavior**
I would expect the values in the past NOT to be displayed as they are out of range within the upper and lower limit.

**Screenshots**
<img width="677" alt="Screen Shot 2019-12-27 at 13 51 25" src="https://user-images.githubusercontent.com/6085036/71519806-e1733380-28b0-11ea-8e2e-645c5f00e2e4.png">

**Desktop (please complete the following information):**
-   OS: Mac
-   Browser: Chrome

**Comment by abhijit945** [comment]
Seems like a valid issue to me. 
@dp21g We'll look into it and add it to our deck. Thanks for the codesandbox snippets, I think everyone who reports an issue should adopt this 👍

**Comment by saket2403** [comment]
On the carbon dev site both past and future dates are being shown 
<img width="1367" alt="Screenshot 2020-01-02 at 1 59 09 PM" src="https://user-images.githubusercontent.com/42207428/71658047-686c5400-2d68-11ea-8d53-e6d383b59366.png">
Consumers are not able to see future dates because [getPadding](https://github.com/cerner/carbon-graphs/blob/master/src/main/js/controls/Gantt/GanttConfig.js#L145-L169) function is missing, similar to the one in Gantt Chart. I added `data.padding.right=10` to the above example and it worked fine.
But I think we should add the function to calculate the padding to fix this issue.
cc @abhijit945

**Comment by abhijit945** [comment]
I see, so the value is there but due to padding its getting cut-off?
Was this always not working? Or did we introduce this recently?

**Comment by saket2403** [comment]
> I see, so the value is there but due to padding its getting cut-off?

Yes
> Was this always not working? Or did we introduce this recently?

Looks like it was always set to default values, ie: Custom padding was not getting applied.

**Comment by dp21g** [comment]
@abhijit945 @saket2403 thanks for the prompt response and fix! great work!

**Comment by dp21g** [comment]
@abhijit945 @saket2403 I am still seeing the issue where the past data points are still visible. Tested in 1.19.0

https://codesandbox.io/s/data-points-displaying-outside-range-test-fix-etfv5

**Comment by abhijit945** [comment]
I am sorry, I was under the assumption that you were not able to see the past data points when padding property was applied. The fix was for that. 
Internally we use d3's `clamp` feature to prevent incorrect rendering of values that are exceeding the Axis bounds. 
Per d3 docs:
```
scale.clamp restricts the output value to the range. Useful to keep data points in the screen — even when their values exceed the domain’s bounds. For example, suppose we want to draw a circle with a surface area proportional to one of our data’s dimensions; but some of our data points might be outside the domain, for example have a negative value.

```

Resolution: If you don't want this behavior then either you extend your X-Axis bounds to accommodate the outlier value or exclude the value that are outside the Axis bounds.
