### ISSUE TITLE
Timeline does not render data points(values) which are the same as the upper limit

### ISSUE THREAD

**Issue by dp21g** [cerner/carbon-graphs#155]
**Describe the bug**
Data points that are exactly the same as the upper limit do not display on the timeline. Whereas data points exactly the same as the lower limit do display.

**To Reproduce**
See working example of issue here:
https://codesandbox.io/s/data-points-same-as-end-date-dont-display-wnc99

**Expected behavior**
The data point should display half of the icon since its on the edge of the timeline.

**Screenshots**
<img width="586" alt="Screen Shot 2020-01-25 at 11 12 48" src="https://user-images.githubusercontent.com/6085036/73120255-afaec480-3f63-11ea-9630-f9edd7311bab.png">

**Desktop (please complete the following information):**
- OS: Mac
- Browser: Chrome

**Comment by saket2403** [comment]
You are setting the left and right padding to 0 in `graph.jsx`. I had fixed this issue in PR #139.  No need to pass any values for Left and Right padding. This [function](https://github.com/cerner/carbon-graphs/blob/master/src/main/js/controls/Timeline/TimelineConfig.js#L21-L42) will set it to default constant padding, and the end values will be displayed. Since you are explicitly setting them to 0 they are not getting displayed. 
cc @dp21g @abhijit945 .

**Comment by abhijit945** [comment]
@dp21g Is there a reason you are having the `padding.right` to 0?

@saket2403 Ideally when the padding is set to 0, we should show the end of axis. The issue is that the end is currently not visible. Having the padding as 5 gives you the desired result which makes me think if we removed a parameter somewhere during our width calculation? 
![image](https://user-images.githubusercontent.com/4908886/73276136-d102f100-41ad-11ea-863f-fa76d2d91aed.png)

**Comment by dp21g** [comment]
The issue is we don't want any default padding since we are trying to match up the ticks to our timeline, having default padding makes it difficult to fit the div container its in from edge to edge.

This is why I'm setting a padding to 0 because there seems to be default padding added to the left and right of the timeline and difficult to synchronise with our Timeline component.

Here it is with our timeline component. I've removed all padding properties. As you can see it is still only displaying certain portion of it, not full width so doesn't sync with the ticks for our timeline.
![Screen Shot 2020-01-28 at 20 10 07](https://user-images.githubusercontent.com/6085036/73301284-646a0f80-420a-11ea-9c75-98f3360591d8.png)

When I only add the Top and Bottom padding to 0, the following is the result. Which is better since now its centring vertically. However the padding on left and right still an issue.
![Screen Shot 2020-01-28 at 20 05 37](https://user-images.githubusercontent.com/6085036/73301693-26b9b680-420b-11ea-80c9-a77bdf5a2da0.png)

so now I add padding to 0 for all which shows the view of the timeline exactly as we want, edge to edge.
![Screen Shot 2020-01-28 at 20 17 53](https://user-images.githubusercontent.com/6085036/73301779-58328200-420b-11ea-8d17-615daef2852b.png)

**Comment by saket2403** [comment]
I am seeing that when we use left and right padding as 0 the X-axis width is becoming more than the canvas width which is the reason for the value getting truncated. But for any other padding values the X-axis width is correctly calculated and applied.
![image](https://user-images.githubusercontent.com/42207428/73714308-7bdb5800-4736-11ea-87b9-f1fae23502b6.png)
![image](https://user-images.githubusercontent.com/42207428/73714336-96153600-4736-11ea-9081-abe3d49c6841.png)
Here are the screenshots of the re-created issue (with 0 padding)  on carbon dev site.
cc @abhijit945
