### ISSUE TITLE
Graph not plotted/partially plotted when the date is mocked and dimension is specified

### ISSUE THREAD

**Issue by JananiGunasekaran** [cerner/carbon-graphs#159]
**Describe the bug**
Graph is not plotted/partially plotted when the date is mocked and dimension is specified. This issue exists only when there are multiple canvases.

**To Reproduce**
1. Mock the date.
2. Specify the dimension property for only one of the graph out of the multiple graphs.
(Works fine when the dimension property is specified for all the multilple graphs).

See working example of issue here:
https://codesandbox.io/s/wonderful-mestorf-nkovn

**Expected behavior**
Graph should get plotted when the date is mocked and dimension is specified.

**Screenshots**
![image](https://user-images.githubusercontent.com/60426528/73347097-06423880-42ad-11ea-918b-fd1303981154.png)

**Desktop (please complete the following information):**

-   OS: Mac
-   Browser Chrome

**Additional context**

**Comment by abhijit945** [comment]
Can you use `mockdate` so that it doesn't impact globally?

**Per my debugging**

In Carbon, the entire graph is an SVG. We use something called as a `clip-path` in our graphs for trimming out anything that we consider out of the graph. The dimensions of the clip-path is usually the width and height of the graph content (or the height specified by the consumer). More info on clip-path can be found here: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-path

It is a common practice in graphing libraries to use `new Date()` for generating unique id for clip-paths for each graph. Usually, since each graph is created at different times it is guaranteed to work.
But in your case, you are using `mockdate` "globally" and any calls to `new Date`  would set to **that** date which would mean any calls made even within Carbon ([for instance](https://github.com/cerner/carbon-graphs/blob/master/src/main/js/core/BaseConfig/helper.js#L60)) would be that as well. 

In this fork: https://codesandbox.io/s/unruffled-dream-73cdm

**Graph 1** has a `dimension` property with height of **90** which would set the clip-path height as 90
![image](https://user-images.githubusercontent.com/4908886/73401792-7488fa00-42b1-11ea-9e59-080b13553e32.png)

**Graph 2** has no `dimension` property but since the `clip-path` `id` is the same now `carbon-1451707200000-clip`, when Graph 2 queries the DOM it will get the clip-path of Graph 1 instead which has the height as 90.
![image](https://user-images.githubusercontent.com/4908886/73401878-a7cb8900-42b1-11ea-97c1-0afa275c8967.png)

**Comment by JananiGunasekaran** [comment]
We have to mock the date to show the last load indicator in the stella timeline for the date specified, which is using new Date.
And i tried using the mockdate so that it doesn't impact globally. But the graph is not plotted completely.

**Comment by abhijit945** [comment]
I would check the DOM element **id** for `svg->defs->clipPath`, if they are same then your mocked date is impacting carbon and not just the input JSON.

**Comment by JananiGunasekaran** [comment]
I have created this fork which contains 4 canvases. 
https://codesandbox.io/s/xenodochial-hodgkin-xor8j
I have specified dimension for first 3 canvases and the 4th canvas has no dimension. I have observed certain scenarios in which the graph is getting plotted completely and in certain cases, the graph is not plotted completely.

These are the few workflows i have tested - below shows the clip-path id and the dimension of the canvas. Its in the same order the canvases are present in the carbon.


Without mocking the date - Graph plotted completely: 
carbon-1580988926107-clip — Dimension not specified
carbon-1580988926235-clip -Dimension not specified
carbon-1580988926263-clip — 290
carbon-1580988926295-clip — 190

With mocking the date - Graph plotted completely:
carbon-1589025600000-clip — 290
carbon-1589025600000-clip — Dimension not specified
carbon-1589025600000-clip — 190
carbon-1589025600000-clip — 190


With mocking the date - Graph not plotted completely:
carbon-1589025600000-clip — Dimension not specified
carbon-1589025600000-clip — Dimension not specified
carbon-1589025600000-clip — 290
carbon-1589025600000-clip — 190

With mocking the date - Graph plotted completely: ( when dimension is not specified for any canvas)
carbon-1589025600000-clip — Dimension not specified
carbon-1589025600000-clip — Dimension not specified
carbon-1589025600000-clip — Dimension not specified
carbon-1589025600000-clip — Dimension not specified


I have 3 dimension sizes - 90, 190, 290 and one canvas has to be without dimension. When i change the dimension of the canvases to different values, in certain cases -  the graph is plotted completely and in certain cases - the graph is not plotted completely.

For instance in the second scenario i have listed above, even after mocking the date and specifying the dimension, the graph is being plotted completely. But if i change the dimension of the 4 canvases to some other values, graph is not completely.
