### ISSUE TITLE
Accessibility: Color Contrast on Bubble Chart

### ISSUE THREAD

**Issue by erinplourde** [cerner/carbon-graphs#180]
Bubble Charts need a palette that meets accessibility guidelines of a contrast ratio of 3:1.

Currently, a range of colors are assigned to bubbles based on the user inputting two colors. This can lead to the steps from color A to color B being inaccessible. 

A color palette will need to be created to help insure that all colors meet WCAG accessibility guidelines. (Possibility of being able to hardcode a color palette instead of creating one based on a two color input?)

<img width="1133" alt="Screen Shot 2020-03-13 at 1 59 22 PM" src="https://user-images.githubusercontent.com/52933964/76651600-d97f7300-6532-11ea-9336-38e2bbf9b2d0.png">

**Comment by scottwilmarth** [comment]
Given the challenges of contrast ratio for such a range of color, could we not just add actual text values to the bubbles to always bee accessible?

**Comment by jeremyfuksa** [comment]
^^^ This advice is likely the best solution. Because with the potential for unlimited data points, it's going to be virtually impossible to get every computed color value to meet 3:1 contrast ratios.

That said, from a tech standpoint, what is the API for making color palette choices? @erinplourde was discussing making some palettes and it seems like the easiest way would be to have an API that accepts a token e.g. "yellow" and then uses a map of predefined color stops for the start and end.

**Comment by erinplourde** [comment]
@laurenbock and I have talked about this. Carbon, historically, has strayed away from having to display text in our graphs due to issues with resizing and translation. We are working to find a solution that helps better pass accessibility standards. 

If possible, for a first pass at accessibility, I would like to give the consumer the option to pass in colors so that they can at least pass in colors that meet 3:1. On the carbon side, we can offer color palette options that a consumer can pick from - similar to how we are doing line charts.

**Comment by laurenbock** [comment]
+1 to @erinplourde's comment - Text within an SVG must resize and translate (move) as the graph moves and timeframes are changed. We would have no way of understanding what it overlaps and if it runs into another word. Additionally, internationalization translations (of the words) would have to be managed by Carbon which isn't a great long-term strategy because each consumer could pass it their own labels. This is why we have stayed away from text within our graphs in Carbon.

**Comment by jeremyfuksa** [comment]
OK. I can understand that. 

I think that WCAG compliance may have to come in stages given the above. Prescribed palettes are a start, but they can't solve the whole problem if a graph has more data points than prescribed colors. UX Foundations and Carbon will need to continue to work together to create a scalable, sustainable solution.

**Comment by jeremyfuksa** [comment]
Removing the design input tag since we've given the input and we know that @erinplourde is working on palettes.

**Comment by chrismichalewicz** [comment]
Added the Requirements Needed label as the Carbon requirements reference the existing color palate and will need to be updated if changes are made to it.

**Comment by jeremyfuksa** [comment]
FYI, @erinplourde @laurenbock , the Terra team tries to make sure that anything labeled as a bug is remedied within 60 days. That's a good metric to hit on Carbon as well. This was labeled as a bug on Mar 16. Is there any update on suggested palettes?

**Comment by jeremyfuksa** [comment]
@scottwilmarth if we add text, do you think we can get close enough on color? A fully-accessible palette will be pretty difficult to achieve.

**Comment by jeremyfuksa** [comment]
I've looked at the palette @erinplourde created and it should allow for sufficient colors that will pass contrast tests.
![Contrast Checking for Bubble Chart](https://user-images.githubusercontent.com/726351/89679474-c345cb00-d8b6-11ea-9a33-4c04035ea953.jpg)
