### ISSUE TITLE
Line Graph Axis Label Truncation

### ISSUE THREAD

**Issue by erinplourde** [cerner/carbon-graphs#208]
A truncation pattern needs to be added for line graphs. Currently carbon will cut off an axis label if it is too long. When a label is too long, it should truncate and upon click reveal the entire label. The label when truncated should also include an '...' to indicate to user that there is more information that is not shown face up. 

This pattern should be consistent with what has been implemented for Gantt charts. (https://engineering.cerner.com/carbon-graphs/#/gantt/label-truncation) 

<img width="654" alt="Screen Shot 2020-04-28 at 4 04 56 PM" src="https://user-images.githubusercontent.com/52933964/80537648-044e4b00-896a-11ea-8466-f454b3a9b09e.png">

**Comment by AshishMotanamGurunadham** [comment]
@erinplourde  @mjhenkes Except pie chart, it looks like we do have same issue for all kind of graphs in carbon. So, please consider updating issue description, so that we can address it in a way to work for all graphs .

cc: @chrismichalewicz @Veera81 @laurenbock

**Comment by AshishMotanamGurunadham** [comment]
@mjhenkes As far as i investigated on this issue, it looks like text-overflow css property does not apply for svg text. Because of this reason we need to go with manual label truncation(validating character length and truncating label according to the height(for y-axis) and  width(for x-axis) of axis). Considering all these things i have implemented logic of label truncation with label consists of all upper case characters as worst case and all lower case characters as best case scenario. Please take a look at the images in attached zip folder to see how label truncation looks on both axis and provide some feedback on those images.

[Truncation images.zip](https://github.com/cerner/carbon-graphs/files/4781358/Truncation.images.zip)

**Comment by chrismichalewicz** [comment]
Removed Requirements Needed label as requirements for there created and documented in CARBON-133
