### ISSUE TITLE
Unable to view multiple regions when combining different graph types into combination graph without hovering on legend

### ISSUE THREAD

**Issue by davidhunt88** [cerner/carbon-graphs#243]
**Describe the bug**
When defining a line graph and paired result graph onto a single graph, I have defined multiple regions to be displayed on the graph. When I do this, the graph shows no regions at all.
I can see the regions themselves are defined and work if I was to hover on the legend for the relevant graph.

**Link to CodeSandbox**

https://codesandbox.io/s/combgraph-region-issue-sy0lk

**Expected behavior**
I require the regions to always show whether you are hovering on a legend or not. I would understand if the regions would still have to match between the 2 graphs in order to show to avoid confusion for users.

**Screenshots**
Issue:
<img width="1720" alt="Screen Shot 2020-06-22 at 3 52 08 pm" src="https://user-images.githubusercontent.com/36438506/85256139-f79c2e00-b4a6-11ea-9a08-dfbbfdf92ef5.png">

**Desktop (please complete the following information):**

-   MacOS Catalina
-   Chrome and IE 11 and above

**Additional context**
This is important for allowing us to draw trending lines between the values of a paired result so that our users can see the trend of Blood Pressure of a patient to catch patient deterioration as soon as possible. Without it, they cannot see the trend as easily and may miss patient deteriorating resulting in patient safety issue.

**Comment by davidhunt88** [comment]
Is it possible to get a timeline for this being looked at please. We need to have a rough date so that we can communicate this on the project

**Comment by AshishMotanamGurunadham** [comment]
In Carbon-graphs, hiding regions(and displaying them when hovering on legend item) in graph when there is more than one content, is not a bug. In that case(when there is more than one content in graph), regions provided should satisfy certain conditions(depends on graph type) in order to display them on graph without hovering on legend item. 

**For Paired Result Graph:**
When there is more than one content in paired result graph  it should satisfy certain conditions to display regions on graph according to code in carbon.  
1. we will check if paired data is proper i.e region for each key(high, mid, low) in value should be there.  
2. it will check if all regions are same or not. (display if regions are same)  
 Based on these conditions we are displaying regions in paired result graph.  

cc:  @mraplumb @Veera81 @sdadn

**Comment by davidhunt88** [comment]
@AshishMotanamGurunadham I did discuss this with you and you told me to raise this as an issue. If you check my sandbox example you will see that the regions between the paired result graph and line graph are identical. It was agreed that this was an issue. We discussed this back on the 22nd June 2020 where I showed you that when you define more than one region on a combination graph, it doesn't matter whether they are the same or not, the regions are hidden till you hover on the legend for the relevant graph. I understand regions should be the same just in this case they are so should be shown.

**Comment by davidhunt88** [comment]
@AshishMotanamGurunadham my fault. I should have read it better. I agree with what you have said for when to display the regions. The logic makes sense and works for me.

**Comment by mraplumb** [comment]
@davidhunt88 at this time we are not planning to make changes to the region logic when there are multiple datasets selected on the graph.  Based on our internal discussion, we feel there is too great of a chance that the resulting graph could reflect misleading information if we were to allow regions associated to multiple datasets to be displayed at the same time.

Based on the example you provided, are you using a combination of graphs to draw a line between the data points in the "high" results of your paired result graph or was that merely a coincidence for the sake of an example.  If that is what you are intending, we could look at an enhancement to provide the line as part of the paired result graph when only one of the results is selected (e.g. High) instead of having to use a combination graph to do that.  This would also allow the regions to continue to be displayed.
![image](https://user-images.githubusercontent.com/44301749/87481937-097c7700-c5f6-11ea-9268-3fb82b059cf6.png)

**Comment by davidhunt88** [comment]
@mraplumb Having the ability to draw a line between values on the paired result graph is exactly what I need and what I was after originally. I was suggested to combine a paired result and line graph by @AshishMotanamGurunadham in order to get round this lack of functionality. If you could add the ability to draw a line between the values of a paired result while maintaining the paired result view that would solve this. As an example, you would define to display high, low and mid values and then draw a line between the values as configured so I could say draw a line between the high values or the low values while displaying everything.

Here are two examples of how we would like it to work from our existing MPage:
![image](https://user-images.githubusercontent.com/36438506/87488339-7558f100-c683-11ea-9fe7-e7735bb71e1a.png)
![image](https://user-images.githubusercontent.com/36438506/87488392-97eb0a00-c683-11ea-820b-811d69d96b4e.png)

**Comment by mraplumb** [comment]
@davidhunt88 after further discussion, we would be comfortable with an enhancement to add the "trend" line linking all the data points in a paired result graph when **only one** of the points is toggled on, via the legend, in the paired result (e.g. high, median, low).
![image](https://user-images.githubusercontent.com/44301749/88409760-01150080-cd9b-11ea-93b3-7d5f6a68e326.png)
When multiple data sets of the paired result are displayed, Carbon would behave as it does today and not display the trend lines.

Based on all previous research into this graph type, we would not want to draw the trend lines across the data points for more than one set of data points in a paired result graph at the same time.

**Comment by davidhunt88** [comment]
@mraplumb so are you saying that you would not have a default trend line draw between the high values when the paired result has all values enabled? The reason I ask is that paired result is most important for Blood Pressure values where by you would have Systolic and Diastolic values logged together with a Mean Pressure on occasion. If you were to implement your solution then, unlike the line graph, there would be no way to draw a trend line between values for Blood pressures while still showing the full paired result.

This could be a problem for clients adopting advanced graphing as well as us using the Carbon library as we need the trend lines between the paired results. If you go ahead with your proposed solution then it will not resolve this issue that I have raised.

Is it possible to understand why there is a hesitation to add a trend line to the paired results without having it appear only when one of the results is toggled on via the legend? If trend lines where added as I mentioned then this would align it to the other graph types like the line graph and would give a consistent implementation approach.

**Comment by mraplumb** [comment]
@davidhunt88 your understanding is correct.  Our UX team has provided this guidance based on research that has been done around each graph type and established design standards.  There is a big concern with showing that much information in a graph face up (paired results, trend lines for each set of values and reference ranges for each set of values) which can lead to confusion for end users.

**Comment by davidhunt88** [comment]
@mraplumb thank you for explaining it. I was hoping we could have something where you would have to pick one of the paired result values.

As an example, if I specify that high is the main result then only defined regions for the high values will show and a trend line would be drawn for the high results. If I defined more regions then the graph would go blank in terms of regions and you would have to hover on the legend to see the regions for that legend on the graph. 

This would then align it to the current solution for combination graphs and would remove any confusion in the graphs with what is being displayed. Is this solution a better one? If it would help, could you let me know who I could discuss this with on the UX team and maybe a call might help better explain this.

Thank you for all your help with this
