### ISSUE TITLE
Timeline X Axis label padding has changed

### ISSUE THREAD

**Issue by abhijit945** [cerner/carbon-graphs#81]
**Describe the bug**
X Axis label has moved down and getting cut-off

**To Reproduce**

1. Go to https://engineering.cerner.com/carbon-graphs/#/timeline/simple

**Expected behavior**

Label should be clearly visible

**Screenshots**

![image](https://user-images.githubusercontent.com/4908886/65151187-2dc5f200-d9eb-11e9-863a-f7f0ff63e325.png)

**Desktop (please complete the following information):**

-   OS: [e.g. iOS] Windows 10
-   Browser [e.g. chrome, safari] Chrome

**Comment by pranav300** [comment]
Investigation
What I have found is that this issue is `OS` specific. In windows chrome and IE the `config.LabelHeights.x` has a value 19, whereas in Mac chrome the value is 17, And for firefox, the difference increases to `3.5`. I have found two solutions for it

1. Increase constant padding `top` from `10` to `20`. But there will always be difference in the value returned by the function `getAxisLabelHeight`

2. To keep a check for OS i.e Win32 and within this have one more check for firefox.
```diff
const getAxisLabelHeight = (label) => {
    const dummy = d3.select("body").append("div");
    const svg = dummy.append("svg");
    const grouper = svg.append("g");
    buildAxisLabel(grouper, label);
-    const height = grouper.node().getBoundingClientRect().height;
+    let height = 0;
+    if (window.navigator.platform === "Win32") {
+        if (window.navigator.userAgent.indexOf("Firefox") > -1) {
+            height = grouper.node().getBoundingClientRect().height - 3.5;
+        } else {
+            height = grouper.node().getBoundingClientRect().height - 2
+        }
+    } else {
+        height = grouper.node().getBoundingClientRect().height;
+   }
    dummy.remove();
    return height;
};
```

**Mentions**
@abhijit945

**Comment by abhijit945** [comment]
As mentioned offline:
I am not sure if we would want to go the browser specific route. Can you try using getBBox instead of getBoundingClientRect and see if we can get away from this browser specific behavior? 
https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

**Comment by pranav300** [comment]
I tried using `getBBox` but, got the same results. So, planning to go ahead with the browser-specific route.

**Comment by ShettyAkarsh** [comment]
@pranav300, yes this issue seems to because of difference in X-axis label height value we are getting in windows.  which in turn effects the transform attribute y-axis position value for this label.

But what i see from this line of code https://github.com/cerner/carbon-graphs/blob/master/src/main/js/controls/Timeline/helpers/creationHelpers.js#L127 is we are adding extra bottom space in calculating the y-axis position for this label by multiplying by 4. i tried multiplying it by 3 it works fine in IE on windows. 
<img width="1680" alt="Screen Shot 2019-10-24 at 2 57 29 PM" src="https://user-images.githubusercontent.com/45097016/67472113-3a82d900-f66e-11e9-9980-a2b134c447f4.png">

could you just check in all the browsers once with this change ?

**Comment by pranav300** [comment]
@ShettyAkarsh, the solution seems to work for all supported browsers except for `Firefox`. It seems to work as it reduces the value of `label height`. But the difference in `label height` value for mac and windows remains the same.

**Comment by pranav300** [comment]
I and @ShettyAkarsh, had a conversation to change [this](https://github.com/cerner/carbon-graphs/blob/master/src/main/js/controls/Timeline/helpers/creationHelpers.js#L94) to `(config.padding.top) * 2 + config.padding.bottom;`. This could be a solution to not go browser and OS-specific. What do you say @abhijit945?

**Comment by abhijit945** [comment]
How different is it visually? Did we also narrow down on why this is happening? There maybe other scenarios (OS dependent, but we just havent _seen_ it yet) we might need to look into based on this investigation.

**Comment by pranav300** [comment]
This is the diff in Mac vs Windows after the change `(config.padding.top) * 2 + config.padding.bottom`
![difference](https://user-images.githubusercontent.com/29273628/68278475-669f5080-0097-11ea-8afe-b95850da34b2.png)

This is the diff in Mac vs windows from changes done in branch [timeline-x-axis-padding-getting-cut](https://github.com/cerner/carbon-graphs/compare/timeline-x-axis-padding-getting-cut)
![image](https://user-images.githubusercontent.com/29273628/68279455-74ee6c00-0099-11ea-89f5-c098d2553c4c.png)
