### ISSUE TITLE
Support native Carbon Panning with Next and Previous navigation

### ISSUE THREAD

**Issue by Prashant-Kamboj** [cerner/carbon-graphs#93]
**Describe the bug**
When we click the buttons in simple Panning-> Line and then go to another graph and resize it then it shows error in the console saying "width is NaN" and since the width is linked with all other elements we get an error in other components too.

**To Reproduce**

1. Click simple in Panning -> Line  
2. Click any other graph and resize the graph
3. See an error in the console.

**Expected behavior**
After we click the buttons in panning and switch to any other graph and resize it there should not be any error in console.

**Screenshots**
![image](https://user-images.githubusercontent.com/53033168/65983088-68736400-e49a-11e9-983b-aeaccb3c9d5f.png)

**Desktop (please complete the following information):**

-   OS: iOS
-   Browser: chrome

**Comment by abhijit945** [comment]
@pranav300 Can we make this as an enhancement? This feels like a much larger work effort than it seems to be (If we are going the `reflow` route)

**Comment by ryanthemanuel** [comment]
@abhijit945 I'd still like to call this a bug (if it's actually a bug).  If it takes longer to fix then so be it

**Comment by ryanthemanuel** [comment]
Actually.  Is this just a bug in the examples?  Or is it an actual bug?

**Comment by abhijit945** [comment]
Panning functionality is **2** part project: 
1. Turn off certain features enabled within graphs that limit overflow of data points given a range. i.e. values such as 250 when the range is 0-200 so that an unbroken line appears at the end of the graph. 
2. Provide `forward`, `backward`, `first` and `last` controls which changes the graph using a mechanism called as `reflow` instead of destroying and recreating the graph. 

The issue in the site is that the next and previous buttons are created but the reflow functionality isnt implemented yet, i.e when you click on the next and previous buttons a new instance of graph is being created, these are the instances the site is no longer aware of and can't destroy when we navigate to another page. 
This is causing a memory leak and leads to console errors. 

Proposal: 
Instead of doing a stop gap in the site, we do the 2nd part correctly and thereby not recreate the graph everytime. An example of reflow is provided [here](https://github.com/cerner/carbon-graphs/pull/114#issuecomment-559114277)

**Comment by ryanthemanuel** [comment]
Given that this is a bug in only the site itself, I'm more inclined to treat this as an enhancement.  We aren't currently breaking any consumers with this.  Marking it as such.
